In [2]:
%cd /content/drive/MyDrive/Colab Notebooks/intron/accentfold/

/content/drive/MyDrive/Colab Notebooks/intron/accentfold

In [4]:
import math
import numpy as np
import pandas as pd
from itertools import islice
from numpy.linalg import norm
from sklearn.metrics.pairwise import cosine_similarity


def sort_dictionary(dict):

    keys = list(dict.keys())
    values = list(dict.values())
    sorted_value_index = np.argsort(values) # in asceding order 
    sorted_dict = {keys[i]: values[i] for i in sorted_value_index}
    return sorted_dict


def compute_distances(points, centroids, k):
    distances = { accent:math.dist(points, list(cent)) for accent, cent in centroids.iterrows()}
    sorted_distances = sort_dictionary(distances)
    top_k = list(sorted_distances.items())[:k]

    return top_k
##cosine sim
def compute_cosine_sim(points, centroids, k):
    distances = {}
    for accent, cent in centroids.iterrows():
        distance= cosine_similarity(np.array(points).reshape(1, -1), np.array(list(cent)).reshape(1, -1))[0][0]
        distances[accent] =distance
    sorted_distances = sort_dictionary(distances)
    top_k = list(sorted_distances.items())[-k:]
    top_k.reverse()

    return top_k

In [19]:
#load centroids
#afrispeech_accents_centroids.csv is in data folder
centroids = pd.read_csv("afrispeech_accents_centroids.csv").set_index("accent")
centroids.head()

,0,1,2,3,4,5,6,7,8,9,...,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023
accent,,,,,,,,,,,,,,,,,,,,,
afemai,-2.546382,-0.576359,0.624049,1.052103,-2.876366,0.290589,0.404536,-0.503575,-0.354989,-3.386981,...,-0.044174,-0.448654,0.670307,0.085151,0.853427,-0.035639,1.662131,0.953181,-1.014886,-0.536698
afo,-1.336637,-0.470084,0.063880,0.335546,-1.851383,-0.396612,-0.536576,-0.373306,-0.090557,-0.492513,...,0.011571,-0.762345,0.165022,0.583999,-0.820598,0.375723,0.382903,0.142690,-0.427723,-0.279608
afrikaans,-0.464128,-1.549197,-0.053204,0.418953,0.255835,0.452912,0.994134,0.140672,0.330566,0.113768,...,0.793572,-0.162218,1.357048,0.109042,0.580104,-0.023817,-0.893144,0.629929,1.331790,0.580449
agatu,-1.833648,0.172555,-0.103170,0.525759,-3.084270,0.485300,-0.591482,-1.441422,0.396092,-0.858426,...,0.335924,-0.568044,-0.496348,0.915912,-1.269462,0.043786,0.287860,-0.410253,-0.952628,-0.235124
akan,0.883080,0.832682,0.103018,-0.027183,0.567259,1.120672,-1.673840,0.122603,0.109325,-1.211770,...,0.294386,-1.187928,0.966112,-0.327402,-0.593723,1.607009,-0.689514,0.843813,0.800687,0.139786

In [20]:
#use euclidean distance 
compute_distances(list(centroids.iloc[5]), centroids, 3)

[('akan (fante)', 0.0),
 ('akan', 19.719489737197172),
 ('twi', 22.971426692862416)]

In [21]:
#use cosine similarity
compute_cosine_sim(list(centroids.iloc[5]), centroids, 3)

[('akan (fante)', 1.0000000000000007),
 ('akan', 0.712881624471096),
 ('twi', 0.6106223561448787)]